Repository googleapis/java-bigqueryconnection, pull requests merged in 2020-05, with the labels that each got.

#8 [CHANGE ME] Re-generated to pick up changes from self.
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionServiceClient.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionServiceSettings.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/package-info.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/stub/ConnectionServiceStub.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/stub/ConnectionServiceStubSettings.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/stub/GrpcConnectionServiceCallableFactory.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/stub/GrpcConnectionServiceStub.java
  google-cloud-bigquery-connection/src/test/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionServiceClientTest.java
  google-cloud-bigquery-connection/src/test/java/com/google/cloud/bigquery/connection/v1beta1/MockConnectionService.java
  google-cloud-bigquery-connection/src/test/java/com/google/cloud/bigquery/connection/v1beta1/MockConnectionServiceImpl.java
  grpc-google-cloud-bigquery-connection-v1beta1/src/main/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionServiceGrpc.java
  proto-google-cloud-bigquery-connection-v1beta1/src/main/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionName.java
  proto-google-cloud-bigquery-connection-v1beta1/src/main/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionProto.java
  proto-google-cloud-bigquery-connection-v1beta1/src/main/java/com/google/cloud/bigquery/connection/v1beta1/LocationName.java
  proto-google-cloud-bigquery-connection-v1beta1/src/main/proto/google/cloud/bigquery/connection/v1beta1/connection.proto
  synth.metadata
Labels: cla: yes

#15 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  .github/workflows/ci.yaml
  .kokoro/build.bat
  synth.metadata
Labels: cla: yes, context: full

#16 docs: update CONTRIBUTING.md to include code formatting (#534)
  CONTRIBUTING.md
  synth.metadata
Labels: cla: yes, context: full

#19 fix: restore GAPIC v2 retry configs
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionServiceClient.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionServiceSettings.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/package-info.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/stub/ConnectionServiceStub.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/stub/ConnectionServiceStubSettings.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/stub/GrpcConnectionServiceStub.java
  google-cloud-bigquery-connection/src/test/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionServiceClientTest.java
  synth.metadata
Labels: cla: yes, context: full

#24 deps: bump shared-deps version and add back certain test deps
  pom.xml
Labels: cla: yes

#30 feat: clean up master branch
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionServiceClient.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionServiceSettings.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/package-info.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/stub/ConnectionServiceStub.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/stub/ConnectionServiceStubSettings.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/stub/GrpcConnectionServiceCallableFactory.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/stub/GrpcConnectionServiceStub.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigqueryconnection/v1/ConnectionServiceClient.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigqueryconnection/v1/ConnectionServiceSettings.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigqueryconnection/v1/package-info.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigqueryconnection/v1/stub/ConnectionServiceStub.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigqueryconnection/v1/stub/ConnectionServiceStubSettings.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigqueryconnection/v1/stub/GrpcConnectionServiceCallableFactory.java
  google-cloud-bigquery-connection/src/main/java/com/google/cloud/bigqueryconnection/v1/stub/GrpcConnectionServiceStub.java
  google-cloud-bigquery-connection/src/test/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionServiceClientTest.java
  google-cloud-bigquery-connection/src/test/java/com/google/cloud/bigquery/connection/v1beta1/MockConnectionService.java
  google-cloud-bigquery-connection/src/test/java/com/google/cloud/bigquery/connection/v1beta1/MockConnectionServiceImpl.java
  google-cloud-bigquery-connection/src/test/java/com/google/cloud/bigqueryconnection/v1/ConnectionServiceClientTest.java
  google-cloud-bigquery-connection/src/test/java/com/google/cloud/bigqueryconnection/v1/MockConnectionService.java
  google-cloud-bigquery-connection/src/test/java/com/google/cloud/bigqueryconnection/v1/MockConnectionServiceImpl.java
Labels: cla: yes

#34 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none
