Repository googleapis/java-bigqueryconnection, pull requests merged in 2020-11, with the labels that each got.

#204 test: add integration test for v1
  .kokoro/build.sh
  google-cloud-bigqueryconnection/pom.xml
  google-cloud-bigqueryconnection/src/test/java/com/google/cloud/bigqueryconnection/v1/it/ITSystemTest.java
Labels: api: bigqueryconnection, cla: yes

#220 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#222 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: bigqueryconnection, cla: yes, context: full

#224 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: bigqueryconnection, automerge, cla: yes, context: full

#230 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryconnection, automerge, cla: yes

#232 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryconnection, automerge, cla: yes

#233 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: bigqueryconnection, cla: yes, context: full

#238 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryconnection, automerge, cla: yes

#239 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryconnection, automerge, cla: yes

#241 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: bigqueryconnection, cla: yes, context: full

#244 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: bigqueryconnection, automerge, cla: yes, context: full

#245 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: bigqueryconnection, automerge, cla: yes, context: full, samples

#246 chore: Remove spurious build warnings by deleting--include_source_info from .bazelrc
  grpc-google-cloud-bigqueryconnection-v1/src/main/java/com/google/cloud/bigquery/connection/v1/ConnectionServiceGrpc.java
  grpc-google-cloud-bigqueryconnection-v1beta1/src/main/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionServiceGrpc.java
  synth.metadata
Labels: api: bigqueryconnection, automerge, cla: yes, context: full
