Repository googleapis/java-bigqueryconnection, pull requests merged in 2020-07, with the labels that each got.

#76 ci(java): run dependency test on Java 8 and 11
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  google-cloud-bigqueryconnection/pom.xml
  grpc-google-cloud-bigqueryconnection-v1/pom.xml
  grpc-google-cloud-bigqueryconnection-v1beta1/pom.xml
  synth.metadata
Labels: cla: yes

#78 [CHANGE ME] Re-generated to pick up changes from googleapis.
  google-cloud-bigqueryconnection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionServiceClient.java
  google-cloud-bigqueryconnection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionServiceSettings.java
  google-cloud-bigqueryconnection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/package-info.java
  google-cloud-bigqueryconnection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/stub/ConnectionServiceStub.java
  google-cloud-bigqueryconnection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/stub/ConnectionServiceStubSettings.java
  google-cloud-bigqueryconnection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/stub/GrpcConnectionServiceStub.java
  google-cloud-bigqueryconnection/src/main/java/com/google/cloud/bigqueryconnection/v1/stub/ConnectionServiceStubSettings.java
  google-cloud-bigqueryconnection/src/test/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionServiceClientTest.java
  synth.metadata
Labels: cla: yes, context: full

#85 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#87 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#90 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#92 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#98 chore: Add/correct PHP namespace for BigQuery connection/reservation
  proto-google-cloud-bigqueryconnection-v1/src/main/java/com/google/cloud/bigquery/connection/v1/ConnectionOuterClass.java
  proto-google-cloud-bigqueryconnection-v1/src/main/proto/google/cloud/bigquery/connection/v1/connection.proto
  proto-google-cloud-bigqueryconnection-v1beta1/src/main/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionProto.java
  proto-google-cloud-bigqueryconnection-v1beta1/src/main/proto/google/cloud/bigquery/connection/v1beta1/connection.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#99 Correct PHP namespace for BigQuery connection
  proto-google-cloud-bigqueryconnection-v1/src/main/java/com/google/cloud/bigquery/connection/v1/ConnectionOuterClass.java
  proto-google-cloud-bigqueryconnection-v1/src/main/proto/google/cloud/bigquery/connection/v1/connection.proto
  synth.metadata
Labels: cla: yes, context: full

#100 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: cla: yes, context: full
