Repository googleapis/java-bigqueryconnection, pull requests merged in 2020-09, with the labels that each got.

#122 chore: fix autorelease script
  .github/workflows/auto-release.yaml
Labels: automerge, cla: yes

#124 chore: update auto-release script to handle undefined
  .github/workflows/auto-release.yaml
Labels: cla: yes

#127 deps: update dependency com.google.cloud:google-cloud-shared-dependen…
  pom.xml
Labels: automerge, cla: yes

#132 build(ci): add Documentation to not-autorelease script
  .github/workflows/auto-release.yaml
Labels: automerge, cla: yes, do not merge

#133 chore: generate CODEOWNERS from templates
  .repo-metadata.json
Labels: automerge, cla: yes

#134 [CHANGE ME] Re-generated to pick up changes from self.
  .github/CODEOWNERS
  synth.metadata
Labels: api: bigqueryconnection, cla: yes, context: none

#135 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#136 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#137 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: bigqueryconnection, cla: yes

#141 chore(ci): skip autorelease workflow on non-release PRs
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: bigqueryconnection, automerge, cla: yes, context: full

#142 chore(ci): verify autorelease release PR content has changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#143 docs(samples): add quick start
  samples/snippets/src/main/java/com/example/bigqueryconnection/QuickstartSample.java
  samples/snippets/src/test/java/com/example/bigqueryconnection/QuickstartSampleIT.java
Labels: cla: yes

#145 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#146 chore(java): use separate autosynth job for README
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#147 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
