Repository googleapis/java-bigqueryconnection, pull requests merged in 2020-10, with the labels that each got.

#148 feat: add aws connection support
  proto-google-cloud-bigqueryconnection-v1/clirr-ignored-differences.xml
  proto-google-cloud-bigqueryconnection-v1/src/main/java/com/google/cloud/bigquery/connection/v1/AwsCrossAccountRole.java
  proto-google-cloud-bigqueryconnection-v1/src/main/java/com/google/cloud/bigquery/connection/v1/AwsCrossAccountRoleOrBuilder.java
  proto-google-cloud-bigqueryconnection-v1/src/main/java/com/google/cloud/bigquery/connection/v1/AwsProperties.java
  proto-google-cloud-bigqueryconnection-v1/src/main/java/com/google/cloud/bigquery/connection/v1/AwsPropertiesOrBuilder.java
  proto-google-cloud-bigqueryconnection-v1/src/main/java/com/google/cloud/bigquery/connection/v1/Connection.java
  proto-google-cloud-bigqueryconnection-v1/src/main/java/com/google/cloud/bigquery/connection/v1/ConnectionOrBuilder.java
  proto-google-cloud-bigqueryconnection-v1/src/main/java/com/google/cloud/bigquery/connection/v1/ConnectionOuterClass.java
  proto-google-cloud-bigqueryconnection-v1/src/main/proto/google/cloud/bigquery/connection/v1/connection.proto
  synth.metadata
Labels: api: bigqueryconnection, cla: yes, context: full

#152 build(ci): set up secrets(env vars) for samples ITs to unblock samples
  .kokoro/build.sh
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/samples.cfg
  synth.py
Labels: automerge, cla: yes

#151 docs(samples): add create and delete connection
  samples/snippets/src/main/java/com/example/bigqueryconnection/CreateConnection.java
  samples/snippets/src/main/java/com/example/bigqueryconnection/DeleteConnection.java
  samples/snippets/src/test/java/com/example/bigqueryconnection/CreateConnectionIT.java
  samples/snippets/src/test/java/com/example/bigqueryconnection/DeleteConnectionIT.java
Labels: api: bigqueryconnection, cla: yes, samples

#154 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#155 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#156 docs(samples): add get connection
  samples/snippets/src/main/java/com/example/bigqueryconnection/GetConnection.java
  samples/snippets/src/test/java/com/example/bigqueryconnection/GetConnectionIT.java
Labels: cla: yes

#157 docs(samples): add list connections
  samples/snippets/src/main/java/com/example/bigqueryconnection/ListConnections.java
  samples/snippets/src/test/java/com/example/bigqueryconnection/ListConnectionsIT.java
Labels: cla: yes

#158 docs(samples): add update connection
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/bigqueryconnection/UpdateConnection.java
  samples/snippets/src/test/java/com/example/bigqueryconnection/UpdateConnectionIT.java
Labels: cla: yes

#159 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes

#161 docs(samples): add share connection
  samples/snippets/src/main/java/com/example/bigqueryconnection/ShareConnection.java
  samples/snippets/src/test/java/com/example/bigqueryconnection/ShareConnectionIT.java
Labels: cla: yes

#163 docs(samples): add create aws connection
  samples/install-without-bom/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/bigqueryconnection/CreateAwsConnection.java
  samples/snippets/src/test/java/com/example/bigqueryconnection/CreateAwsConnectionIT.java
Labels: api: bigqueryconnection, automerge, cla: yes, samples

#164 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes

#170 ci: restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
Labels: automerge, cla: yes

#171 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes

#175 ci(java): suggest formatting fixes
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: bigqueryconnection, cla: yes, context: full

#182 refactor(samples): update names
  samples/snippets/src/test/java/com/example/bigqueryconnection/CreateAwsConnectionIT.java
  samples/snippets/src/test/java/com/example/bigqueryconnection/CreateConnectionIT.java
  samples/snippets/src/test/java/com/example/bigqueryconnection/DeleteConnectionIT.java
  samples/snippets/src/test/java/com/example/bigqueryconnection/GetConnectionIT.java
  samples/snippets/src/test/java/com/example/bigqueryconnection/ListConnectionsIT.java
  samples/snippets/src/test/java/com/example/bigqueryconnection/ShareConnectionIT.java
  samples/snippets/src/test/java/com/example/bigqueryconnection/UpdateConnectionIT.java
Labels: cla: yes

#181 build(java): auto-approve README regeneration
  .github/workflows/approve-readme.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#183 chore: add property tag for shared-deps
  pom.xml
Labels: cla: yes

#187 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#188 build(java): enable snippet-bot
  .github/snippet-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#193 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#195 chore: clean up and update renovate.json
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#198 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: cla: yes, context: full

#202 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#205 feat: promote to 1.0.0
  .repo-metadata.json
Labels: cla: yes

#207 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#208 ci: add secrets for ITs
  .kokoro/nightly/integration.cfg
  .kokoro/presubmit/integration.cfg
  synth.py
Labels: cla: yes

#209 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#212 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes
