Repository googleapis/java-bigqueryconnection, pull requests merged in 2021-04, with the labels that each got.

#357 build(java): skip javadoc tests during dependencies test
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: bigqueryconnection, cla: yes, context: full

#358 deps: update dependency com.google.cloud:google-cloud-shared-dependencies to v0.21.0
  pom.xml
Labels: api: bigqueryconnection, automerge, cla: yes

#367 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryconnection, cla: yes

#369 fix: release scripts from issuing overlapping phases
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: bigqueryconnection, automerge, cla: yes, context: full

#385 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryconnection, automerge, cla: yes
