Repository googleapis/java-bigqueryconnection, pull requests merged in 2021-02, with the labels that each got.

#296 build(java): generate docfx yml on release
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigqueryconnection, cla: yes, context: full

#297 build(java): run linkage monitor as GitHub action
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  synth.metadata
Labels: api: bigqueryconnection, cla: yes, context: full

#298 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: bigqueryconnection, cla: yes, context: full

#299 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: api: bigqueryconnection, automerge, cla: yes, context: full

#300 docs: generate sample code in the Java microgenerator
  google-cloud-bigqueryconnection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionServiceClient.java
  google-cloud-bigqueryconnection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/package-info.java
  google-cloud-bigqueryconnection/src/main/java/com/google/cloud/bigqueryconnection/v1/ConnectionServiceClient.java
  google-cloud-bigqueryconnection/src/main/java/com/google/cloud/bigqueryconnection/v1/package-info.java
  synth.metadata
Labels: automerge, cla: yes, context: full, samples

#303 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: bigqueryconnection, cla: yes, context: full

#306 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: bigqueryconnection, automerge, cla: yes, context: full

#305 chore: update gapic-generator-java to 0.0.20
  google-cloud-bigqueryconnection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/stub/GrpcConnectionServiceStub.java
  google-cloud-bigqueryconnection/src/main/java/com/google/cloud/bigqueryconnection/v1/stub/GrpcConnectionServiceStub.java
  google-cloud-bigqueryconnection/src/test/java/com/google/cloud/bigquery/connection/v1beta1/MockConnectionServiceImpl.java
  google-cloud-bigqueryconnection/src/test/java/com/google/cloud/bigqueryconnection/v1/MockConnectionServiceImpl.java
  synth.metadata
Labels: api: bigqueryconnection, cla: yes, context: full

#307 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigqueryconnection, cla: yes, context: full

#309 build: reduce download junk in log files
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: bigqueryconnection, automerge, cla: yes, context: full

#312 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-bigqueryconnection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/gapic_metadata.json
  google-cloud-bigqueryconnection/src/main/java/com/google/cloud/bigqueryconnection/v1/gapic_metadata.json
  synth.metadata
Labels: api: bigqueryconnection, automerge, cla: yes, context: full

#313 ci: test out new sonatype google endpoint
  google-cloud-bigqueryconnection-bom/pom.xml
  pom.xml
Labels: api: bigqueryconnection, automerge, cla: yes

#316 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryconnection, automerge, cla: yes

#326 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryconnection, automerge, cla: yes

#330 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryconnection, automerge, cla: yes
