Repository googleapis/java-bigqueryconnection, pull requests merged in 2021-05, with the labels that each got.

#389 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: bigqueryconnection, automerge, cla: yes, context: none

#390 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: bigqueryconnection, automerge, cla: yes

#392 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigqueryconnection, cla: yes, context: full

#398 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryconnection, automerge, cla: yes

#400 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: bigqueryconnection, automerge, cla: yes, context: full

#404 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryconnection, automerge, cla: yes

#407 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigqueryconnection, automerge, cla: yes, context: full

#406 chore: release gapic-generator-java v1.0.5
  google-cloud-bigqueryconnection/src/main/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionServiceClient.java
  google-cloud-bigqueryconnection/src/test/java/com/google/cloud/bigquery/connection/v1beta1/ConnectionServiceClientTest.java
  synth.metadata
Labels: api: bigqueryconnection, cla: yes, context: full

#412 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryconnection, automerge, cla: yes

#413 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: bigqueryconnection, automerge, cla: yes, context: full
